name = "anbe-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "anbe-db"
database_id = "37675f7b-d542-4e1c-b30b-cb7b92bb9ff1"

[[kv_namespaces]]
binding = "SESSIONS"
id = "6ac8ec802f1046589dd1c168be93b8d7"

[vars]
ENVIRONMENT = "production"

# Secrets — set via: wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_PASSWORD_HASH
